name: keepassxc
version: 2.1.4
grade: stable
summary: community driven port of the windows application “Keepass Password Safe”
description: |
  KeePassXC is an application for people with extremely high demands on secure
  personal data management. It has a light interface, is cross platform and
  is published under the terms of the GNU General Public License.
confinement: strict

apps:
  keepassxc:
    command: desktop-launch keepassxc
    plugs: [unity7, x11, opengl, gsettings, home, network, network-bind, removable-media]

parts:
  keepassxc:
    source: .
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_TESTS=OFF
      - -DWITH_XC_AUTOTYPE=ON
      - -DWITH_XC_HTTP=ON
    build-packages:
      - g++
      - libgcrypt20-dev
      - libqt5x11extras5-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - zlib1g-dev
      - libxi-dev
      - libxtst-dev
    after: [desktop-qt5]
